# Generated by Django 4.1.3 on 2022-12-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="position",
            field=models.CharField(default="Cook", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(null=True),
        ),
    ]
